[package]
description = "Rust ADB (Android Debug Bridge) client library"
edition = "2021"
keywords = ["adb", "android"]
license = "MIT"
name = "adb_client"
readme = "README.md"
repository = "https://github.com/cocool97/adb_client"
version = "0.5.0"

[lib]
name = "adb_client"
path = "src/lib.rs"

[[example]]
name = "adb_cli"
path = "examples/adb_cli.rs"

[dependencies]
byteorder = "1.4.3"
regex = { version = "1.7.3", features = ["perf", "std", "unicode"] }
termios = { version = "0.3.3" }
thiserror = { version = "1.0.40" }

## Binary-only dependencies
## Marked as optional so that lib users do not depend on them
[dev-dependencies]
clap = { version = "= 4.2.1", features = ["derive"] }
